packages:
  - apps/*
  - packages/*
  - scripts/*

onlyBuiltDependencies:
  - '@openapitools/openapi-generator-cli'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
