/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FakeoverFlowBackendHttpApiFeaturesAuthAvailableAvailableAvailabilityType } from './fakeoverFlowBackendHttpApiFeaturesAuthAvailableAvailableAvailabilityType';


export interface FakeoverFlowBackendHttpApiFeaturesAuthAvailableAvailableRequest { 
    type?: FakeoverFlowBackendHttpApiFeaturesAuthAvailableAvailableAvailabilityType;
    value: string;
}
export namespace FakeoverFlowBackendHttpApiFeaturesAuthAvailableAvailableRequest {
}


