/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FakeoverFlowBackendHttpApiFeaturesPostsContentsListContentsListContentsUserActivity } from './fakeoverFlowBackendHttpApiFeaturesPostsContentsListContentsListContentsUserActivity';


export interface FakeoverFlowBackendHttpApiFeaturesPostsContentsListContentsListContentsPostContent { 
    id?: string;
    postId?: string;
    content?: string;
    isInternal?: boolean;
    createdOn?: FakeoverFlowBackendHttpApiFeaturesPostsContentsListContentsListContentsUserActivity;
}

