/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest { 
    title: string;
    content: string;
    tags?: Array<string>;
}

