/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FakeoverFlowBackendHttpApiFeaturesPostsListPostsListPostsPostSummary { 
    postId?: string;
    title?: string;
    content?: string;
    tags?: Array<string>;
    views?: number;
    votes?: number;
    userId?: string;
    userName?: string;
    createdOn?: string;
}

