/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostUserActivity } from './fakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostUserActivity';
import { FakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostUserVote } from './fakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostUserVote';


export interface FakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostResponse { 
    postId?: string;
    title?: string;
    content?: string;
    contentId?: string;
    tags?: Array<string>;
    createdOn?: FakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostUserActivity;
    updatedOn?: FakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostUserActivity | null;
    views?: number;
    userVote?: FakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostUserVote | null;
    upvotes?: number;
    downvotes?: number;
}

