/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FakeoverFlowBackendHttpApiFeaturesTagsListTagsListTagsTags { 
    value?: string;
    id?: number;
    postCount?: number;
}

