/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export const FakeoverFlowBackendHttpApiFeaturesAuthLoginLoginAuthenticationType = {
    Credentials: 'Credentials',
    Google: 'Google'
} as const;
export type FakeoverFlowBackendHttpApiFeaturesAuthLoginLoginAuthenticationType = typeof FakeoverFlowBackendHttpApiFeaturesAuthLoginLoginAuthenticationType[keyof typeof FakeoverFlowBackendHttpApiFeaturesAuthLoginLoginAuthenticationType];

