/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FakeoverFlowBackendHttpApiFeaturesPostsListPostsListPostsPostSummary } from './fakeoverFlowBackendHttpApiFeaturesPostsListPostsListPostsPostSummary';


export interface FakeoverFlowBackendHttpApiFeaturesPostsListPostsListPostsResponse { 
    posts?: Array<FakeoverFlowBackendHttpApiFeaturesPostsListPostsListPostsPostSummary>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
}

