/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FakeoverFlowBackendHttpApiFeaturesAuthSignupSignupRequest { 
    email: string;
    password?: string;
    firstName: string;
    lastName: string;
    username: string;
}

