/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FakeoverFlowBackendHttpApiFeaturesAuthLoginLoginResponse } from './fakeoverFlowBackendHttpApiFeaturesAuthLoginLoginResponse';


export interface MicrosoftAspNetCoreHttpHttpResultsOkOfResponse2 { 
    value?: FakeoverFlowBackendHttpApiFeaturesAuthLoginLoginResponse | null;
    statusCode?: number;
}

