/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FakeoverFlowBackendHttpApiFeaturesAuthRefreshRefreshResponse } from './fakeoverFlowBackendHttpApiFeaturesAuthRefreshRefreshResponse';


export interface MicrosoftAspNetCoreHttpHttpResultsOkOfResponse { 
    value?: FakeoverFlowBackendHttpApiFeaturesAuthRefreshRefreshResponse | null;
    statusCode?: number;
}

