/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { FakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest } from '../model/fakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest';
// @ts-ignore
import { FakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentResponse } from '../model/fakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentResponse';
// @ts-ignore
import { FakeoverFlowBackendHttpApiFeaturesPostsContentsListContentsListContentsResponse } from '../model/fakeoverFlowBackendHttpApiFeaturesPostsContentsListContentsListContentsResponse';
// @ts-ignore
import { FakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest } from '../model/fakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest';
// @ts-ignore
import { FakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentResponse } from '../model/fakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentResponse';
// @ts-ignore
import { FakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest } from '../model/fakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest';
// @ts-ignore
import { FakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsResponse } from '../model/fakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsResponse';
// @ts-ignore
import { FakeoverFlowBackendHttpApiFeaturesPostsListPostsListPostsResponse } from '../model/fakeoverFlowBackendHttpApiFeaturesPostsListPostsListPostsResponse';
// @ts-ignore
import { FakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostResponse } from '../model/fakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostResponse';
// @ts-ignore
import { FastEndpointsErrorResponse } from '../model/fastEndpointsErrorResponse';
// @ts-ignore
import { FastEndpointsProblemDetails } from '../model/fastEndpointsProblemDetails';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class PostService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @param postId 
     * @param fakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createAnswer(postId: string, fakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest: FakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<FakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentResponse>;
    public createAnswer(postId: string, fakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest: FakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<FakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentResponse>>;
    public createAnswer(postId: string, fakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest: FakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<FakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentResponse>>;
    public createAnswer(postId: string, fakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest: FakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (postId === null || postId === undefined) {
            throw new Error('Required parameter postId was null or undefined when calling createAnswer.');
        }
        if (fakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest === null || fakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest === undefined) {
            throw new Error('Required parameter fakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest was null or undefined when calling createAnswer.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (JWTBearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JWTBearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/post/${this.configuration.encodeParam({name: "postId", value: postId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/contents`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<FakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: fakeoverFlowBackendHttpApiFeaturesPostsContentsCreateContentCreateContentRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param fakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createPost(fakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest: FakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<FakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsResponse>;
    public createPost(fakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest: FakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<FakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsResponse>>;
    public createPost(fakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest: FakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<FakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsResponse>>;
    public createPost(fakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest: FakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (fakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest === null || fakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest === undefined) {
            throw new Error('Required parameter fakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest was null or undefined when calling createPost.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (JWTBearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JWTBearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/post`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<FakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: fakeoverFlowBackendHttpApiFeaturesPostsCreatePostsPostsRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param postId 
     * @param contentId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteVote(postId: string, contentId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public deleteVote(postId: string, contentId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public deleteVote(postId: string, contentId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public deleteVote(postId: string, contentId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (postId === null || postId === undefined) {
            throw new Error('Required parameter postId was null or undefined when calling deleteVote.');
        }
        if (contentId === null || contentId === undefined) {
            throw new Error('Required parameter contentId was null or undefined when calling deleteVote.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (JWTBearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JWTBearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/post/${this.configuration.encodeParam({name: "postId", value: postId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/contents/${this.configuration.encodeParam({name: "contentId", value: contentId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "guid"})}/votes`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPostById(id: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<FakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostResponse>;
    public getPostById(id: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<FakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostResponse>>;
    public getPostById(id: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<FakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostResponse>>;
    public getPostById(id: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getPostById.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/post/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<FakeoverFlowBackendHttpApiFeaturesPostsViewPostViewPostResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param postId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listAnswers(postId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<FakeoverFlowBackendHttpApiFeaturesPostsContentsListContentsListContentsResponse>;
    public listAnswers(postId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<FakeoverFlowBackendHttpApiFeaturesPostsContentsListContentsListContentsResponse>>;
    public listAnswers(postId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<FakeoverFlowBackendHttpApiFeaturesPostsContentsListContentsListContentsResponse>>;
    public listAnswers(postId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (postId === null || postId === undefined) {
            throw new Error('Required parameter postId was null or undefined when calling listAnswers.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/post/${this.configuration.encodeParam({name: "postId", value: postId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/contents`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<FakeoverFlowBackendHttpApiFeaturesPostsContentsListContentsListContentsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param searchTerm 
     * @param tag 
     * @param page 
     * @param pageSize 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listPosts(searchTerm?: string, tag?: string, page?: number, pageSize?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<FakeoverFlowBackendHttpApiFeaturesPostsListPostsListPostsResponse>;
    public listPosts(searchTerm?: string, tag?: string, page?: number, pageSize?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<FakeoverFlowBackendHttpApiFeaturesPostsListPostsListPostsResponse>>;
    public listPosts(searchTerm?: string, tag?: string, page?: number, pageSize?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<FakeoverFlowBackendHttpApiFeaturesPostsListPostsListPostsResponse>>;
    public listPosts(searchTerm?: string, tag?: string, page?: number, pageSize?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>searchTerm, 'searchTerm');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>tag, 'tag');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/post`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<FakeoverFlowBackendHttpApiFeaturesPostsListPostsListPostsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param postId 
     * @param contentId 
     * @param fakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public voteContent(postId: string, contentId: string, fakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest: FakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<FakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentResponse>;
    public voteContent(postId: string, contentId: string, fakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest: FakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<FakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentResponse>>;
    public voteContent(postId: string, contentId: string, fakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest: FakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<FakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentResponse>>;
    public voteContent(postId: string, contentId: string, fakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest: FakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (postId === null || postId === undefined) {
            throw new Error('Required parameter postId was null or undefined when calling voteContent.');
        }
        if (contentId === null || contentId === undefined) {
            throw new Error('Required parameter contentId was null or undefined when calling voteContent.');
        }
        if (fakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest === null || fakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest === undefined) {
            throw new Error('Required parameter fakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest was null or undefined when calling voteContent.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (JWTBearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('JWTBearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/post/${this.configuration.encodeParam({name: "postId", value: postId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/contents/${this.configuration.encodeParam({name: "contentId", value: contentId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "guid"})}/votes`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<FakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: fakeoverFlowBackendHttpApiFeaturesPostsContentsVotesVoteContentVoteContentRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
