START TRANSACTION;
DROP INDEX public."IX_PostContent_PostId_ContentType";

ALTER TABLE public."Posts" DROP COLUMN "Votes";

ALTER TABLE public."PostContent" ADD "PostsId" text;

ALTER TABLE public."PostContent" ADD "Votes" bigint NOT NULL DEFAULT 0;

CREATE TABLE public."Tag" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Value" character varying(50) NOT NULL,
    "Description" character varying(200) NOT NULL DEFAULT '',
    "Color" character varying(20) NOT NULL,
    "VectorText" tsvector GENERATED ALWAYS AS (to_tsvector('english', "Value" || ' ' || "Description")) STORED NOT NULL,
    CONSTRAINT "PK_Tag" PRIMARY KEY ("Id")
);

CREATE TABLE public."Votes" (
    "UserId" uuid NOT NULL,
    "ContentId" uuid NOT NULL,
    "UpVote" boolean NOT NULL,
    CONSTRAINT "PK_Votes" PRIMARY KEY ("UserId", "ContentId"),
    CONSTRAINT "FK_Votes_PostContent_ContentId" FOREIGN KEY ("ContentId") REFERENCES public."PostContent" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Votes_UserAccounts_UserId" FOREIGN KEY ("UserId") REFERENCES public."UserAccounts" ("Id") ON DELETE CASCADE
);

CREATE TABLE public."PostTags" (
    "TagId" integer NOT NULL,
    "PostId" text NOT NULL,
    CONSTRAINT "PK_PostTags" PRIMARY KEY ("PostId", "TagId"),
    CONSTRAINT "FK_PostTags_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES public."Posts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PostTags_Tag_TagId" FOREIGN KEY ("TagId") REFERENCES public."Tag" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_PostContent_PostId_ContentType" ON public."PostContent" ("PostId", "ContentType") WHERE "ContentType" = 'questions';

CREATE INDEX "IX_PostContent_PostsId" ON public."PostContent" ("PostsId");

CREATE INDEX "IX_PostTags_TagId" ON public."PostTags" ("TagId");

CREATE UNIQUE INDEX "IX_Tag_Value" ON public."Tag" ("Value");

CREATE INDEX "IX_Tag_VectorText" ON public."Tag" USING GIN ("VectorText");

CREATE INDEX "IX_Votes_ContentId" ON public."Votes" ("ContentId");

ALTER TABLE public."PostContent" ADD CONSTRAINT "FK_PostContent_Posts_PostsId" FOREIGN KEY ("PostsId") REFERENCES public."Posts" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251101102351_add_post_votes_tags', '9.0.9');

COMMIT;

