// <auto-generated />
using System;
using FakeoverFlow.Backend.Http.Api;
using FakeoverFlow.Backend.Http.Api.Models.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace FakeoverFlow.Backend.Http.Api.Migrations
{
    
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_roles", new[] { "admin", "moderator", "user" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FakeoverFlow.Backend.Http.Api.Models.Accounts.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte[]>("Password")
                        .HasColumnType("bytea");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<UserRoles>("Role")
                        .HasColumnType("user_roles");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<NpgsqlTsVector>("VectorText")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "FirstName", "LastName", "Email", "Username" });

                    b.Property<DateTimeOffset?>("VerifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("IX_UserAccount_CreatedOn");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_UserAccount_IsDeleted_ActiveOnly")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("UpdatedOn")
                        .HasDatabaseName("IX_UserAccount_UpdatedOn");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("VectorText");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("VectorText"), "GIN");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("FakeoverFlow.Backend.Http.Api.Models.Accounts.UserAccountVerification", b =>
                {
                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("VerificationToken");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserAccountVerifications");
                });

            modelBuilder.Entity("FakeoverFlow.Backend.Http.Api.Models.Accounts.UserAccount", b =>
                {
                    b.OwnsOne("FakeoverFlow.Backend.Http.Api.Models.Accounts.UserAccountSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uuid");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccounts");

                            b1.ToJson("Settings");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("FakeoverFlow.Backend.Http.Api.Models.Accounts.UserAccountVerification", b =>
                {
                    b.HasOne("FakeoverFlow.Backend.Http.Api.Models.Accounts.UserAccount", "Account")
                        .WithOne()
                        .HasForeignKey("FakeoverFlow.Backend.Http.Api.Models.Accounts.UserAccountVerification", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
