/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FakeoverFlowBackendHttpApiFeaturesAuthLoginLoginAuthenticationType } from './fakeoverFlowBackendHttpApiFeaturesAuthLoginLoginAuthenticationType';


export interface FakeoverFlowBackendHttpApiFeaturesAuthLoginLoginRequest { 
    type?: FakeoverFlowBackendHttpApiFeaturesAuthLoginLoginAuthenticationType;
    data?: { [key: string]: string; };
}
export namespace FakeoverFlowBackendHttpApiFeaturesAuthLoginLoginRequest {
}


