/**
 * FakeoverFlow.Backend.Http.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FakeoverFlowBackendHttpApiFeaturesAuthRefreshRefreshResponse { 
    accessToken?: string;
    refreshToken?: string;
    accessTokenExpires?: string;
    refreshTokenExpires?: string;
}

